version: '3.8'
services:
  app:
    build:
      context: .
    ports:
    - 3000:3000
    environment:
    # Does nothing, just as an example
    - MY_VARIABLE=0
    volumes:
    - ./:/app
    command: yarn start
